version: 0.0
os: linux
files:
  - source: published/s.zip
    destination: /app
hooks:
  AfterInstall:
   - location: ./codedeploy/afterInstall.sh
     timeout: 300
     runas: ubuntu
  BeforeInstall:
     - location: ./codedeploy/beforeinstall.sh
       timeout: 300
       runas: ubuntu
  ApplicationStart:
   - location: ./codedeploy/applicationStart.sh
     timeout: 300
     runas: ubuntu
  ApplicationStop:
   - location: ./codedeploy/applicationStop.sh
     timeout: 300
     runas: ubuntu
